name: journal
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^2.13.0
  flutter_svg: ^2.0.6
  bloc: ^8.1.2
  equatable: ^2.0.5
  cached_network_image: ^3.2.3
  google_fonts: ^4.0.4
  shared_preferences: ^2.1.1
  flutter_onboarding_slider: ^1.0.9
  sqflite: ^2.2.8+4
  connectivity_plus: ^4.0.1
  uuid: ^3.0.7
  sqflite_migration: ^0.3.0
  path: ^1.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:

  uses-material-design: true
  assets:
  - assets/svg/
